const HovedpunkterTekster = {
    'hovedpunkter.tittel.bekreft': 'Bekreft og send søknaden',
    'hovedpunkter.ingress': 'Sjekk at du har fått med alle nødvendige opplysninger og kvitteringer.<br/>Når du sender søknaden, går den til NAV.',
    'hovedpunkter.tittel': 'Hovedpunkter fra søknaden',
    'hovedpunkter.undertittel': 'Opplastede kvitteringer',
    'hovedpunkter.fra_til': 'Du søker om reisetilskudd for <strong>%FRA% til %TIL%</strong>',
    'hovedpunkter.arbeidsgiver_betaler-ikke': 'Du har krysset av for at arbeidsgiveren din ikke legger ut for utgiftene. Reisetilskuddet fra NAV utbetales til deg.',
    'hovedpunkter.kvitteringer': 'Du har lagt ved <strong>%ANTALL% utgifter</strong> på til sammen <strong>%SUM% kroner</strong>.',
    'hovedpunkter.bekreft.tekst': 'Jeg har lest informasjonen jeg har fått underveis i søknaden og bekrefter at opplysningene jeg har gitt er korrekte. Jeg bekrefter også at jeg har lest og forstått ',
    'hovedpunkter.bekreft.lenke': ' hvilke plikter jeg har',
    'hovedpunkter.plikter.tittel': 'Viktig å være klar over',
    'hovedpunkter.plikter.tilskudd': 'Du kan få reisetilskudd hvis du fyller kravene du finner på ',
    'hovedpunkter.plikter.tilskudd.lenke': 'nav.no/reisetilskudd',
    'hovedpunkter.plikter.tilskudd.url': 'https://nav.no/reisetilskudd',
    'hovedpunkter.plikter.viktig': 'Viktig å være klar over',
    'hovedpunkter.plikter.punkter.punkt1': 'Fristen for å søke reisetilskudd er som hovedregel 3 måneder.',
    'hovedpunkter.plikter.punkter.punkt2': 'NAV kan innhente opplysninger som er nødvendige for å behandle søknaden.',
    'hovedpunkter.plikter.punkter.punkt3': 'Du kan miste retten til penger hvis opplysningene dine ikke er riktige.',
    'hovedpunkter.plikter.punkter.punkt4': 'NAV kan holde igjen eller kreve tilbake penger.',
    'hovedpunkter.plikter.punkter.punkt5': 'Å gi feil opplysninger kan være straffbart.',
    'hovedpunkter.send-knapp.tekst': 'Send inn søknaden',
    'hovedpunkter.videre-knapp.tekst': 'Gå videre',
    'hovedpunkter.lagre-knapp.tekst': 'Lagre og lukk',
}

export default HovedpunkterTekster
