export enum TagTyper {
    ANSVARSERKLARING = 'ANSVARSERKLARING',
    TRANSPORT_TIL_DAGLIG = 'TRANSPORT_TIL_DAGLIG',
    TYPE_TRANSPORT = 'TYPE_TRANSPORT',
    OFFENTLIG_TRANSPORT_TIL_DAGLIG = 'OFFENTLIG_TRANSPORT_TIL_DAGLIG',
    OFFENTLIG_TRANSPORT_BELOP = 'OFFENTLIG_TRANSPORT_BELOP',
    BIL_TIL_DAGLIG = 'BIL_TIL_DAGLIG',
    KM_HJEM_JOBB = 'KM_HJEM_JOBB',
    REISE_MED_BIL = 'REISE_MED_BIL',
    BIL_DATOER = 'BIL_DATOER',
    KVITTERINGER = 'KVITTERINGER',
    UTBETALING = 'UTBETALING',
    BEKREFT_OPPLYSNINGER = 'BEKREFT_OPPLYSNINGER',
    VAER_KLAR_OVER_AT = 'VAER_KLAR_OVER_AT',
    HVOR_MYE_PROSENT_VERDI = 'HVOR_MYE_PROSENT_VERDI',
    PERIODER = 'PERIODER',
    UTDANNING = 'UTDANNING',
}

export enum SvarEnums {
    JA = 'JA',
    NEI = 'NEI',
    CHECKED = 'CHECKED',
    UNCHECKED = 'UNCHECKED'
}

export enum UtgiftTyper {
    OFFENTLIG_TRANSPORT = 'OFFENTLIG_TRANSPORT',
    TAXI = 'TAXI',
    PARKERING = 'PARKERING',
    BOMPENGER = 'BOMPENGER',
    ANNET = 'ANNET'
}
